### ISSUE TITLE
No detection visible

### ISSUE THREAD

**Issue by cosama** [tjuskyzhang/Scaled-YOLOv4-TensorRT#5]
Thanks for working on moving yolov4-tiny to tensorrt.

I tried the repo, it all runs but there are no bounding boxes displayed on the resulting images, it looks like it doesn't detect anything.

The only difference to the setup you mentioned in your readme is that I used the official weights from https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v4_pre/yolov4-tiny.weights as I don't have access to baidu, when creating the wts file. Also https://github.com/WongKinYiu/PyTorch_YOLOv4 seems to not work with the gen_wts.py file anymore, I had to modify it slightly by manually importing darknet.

Any idea what is going on here? Have you had some successful detection in the past?

**Comment by tjuskyzhang** [comment]
> Thanks for working on moving yolov4-tiny to tensorrt.
> 
> I tried the repo, it all runs but there are no bounding boxes displayed on the resulting images, it looks like it doesn't detect anything.
> 
> The only difference to the setup you mentioned in your readme is that I used the official weights from https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v4_pre/yolov4-tiny.weights as I don't have access to baidu, when creating the wts file. Also https://github.com/WongKinYiu/PyTorch_YOLOv4 seems to not work with the gen_wts.py file anymore, I had to modify it slightly by manually importing darknet.
> 
> Any idea what is going on here? Have you had some successful detection in the past?

 You can directly download the weights from https://github.com/WongKinYiu/PyTorch_YOLOv4/tree/master and I think you will get the right detection results.

There is a little different between the AlexeyAB's version and WongKinYiu's version. At the route layer,  AlexeyAB uses "groups=2 group_id=1" , and WongKinYiu uses "route_lhalf". The dimensions of the tensors are same, so "it all runs". But the weights are different, so "it doesn't detect anything".

**Comment by cosama** [comment]
Thanks so much for pointing this out. I tried converting the [pt](https://drive.google.com/file/d/1aQKcCvTAl1uOWzzHVE9Z8Ixgikc3AuYQ/view?usp=sharing) file and it works indeed now. It runs at 30ms/frame on a TX2 pretty impressive.

Also thanks for the explanation I clearly was missing something there.

**Comment by tjuskyzhang** [comment]
> Thanks so much for pointing this out. I tried converting the [pt](https://drive.google.com/file/d/1aQKcCvTAl1uOWzzHVE9Z8Ixgikc3AuYQ/view?usp=sharing) file and it works indeed now. It runs at 30ms/frame on a TX2 pretty impressive.
> 
> Also thanks for the explanation I clearly was missing something there.

I also test on TX2. When I using the MAX-N mode and jetson_clocks, it can run about 10~11ms/frame.

**Comment by swapgit** [comment]
> Thanks so much for pointing this out. I tried converting the [pt](https://drive.google.com/file/d/1aQKcCvTAl1uOWzzHVE9Z8Ixgikc3AuYQ/view?usp=sharing) file and it works indeed now. It runs at 30ms/frame on a TX2 pretty impressive.
> 
> Also thanks for the explanation I clearly was missing something there.

@cosama can you give some more details over this i take latest pull from [PyTorch_YOLOv4](https://github.com/WongKinYiu/PyTorch_YOLOv4/tree/u3_preview) repo, also downloaded same pytorch [weights](https://drive.google.com/file/d/1aQKcCvTAl1uOWzzHVE9Z8Ixgikc3AuYQ/view?usp=sharing) provided by the author but still facing similar issue as [here](https://github.com/tjuskyzhang/Scaled-YOLOv4-TensorRT/issues/20).

**Comment by cosama** [comment]
@swapgit Sorry I have never had an issue like that, also I don't really have a setup anymore to work on this sorry.

Given that the original issue was resolved I will close this.
